language: go

# env: GO111MODULE=on GOFLAGS='-mod vendor'
#env: GO111MODULE=on

# You don't need to test on very old versions of the Go compiler. It's the user's
# responsibility to keep their compiler up to date.
go:
  - 1.14.x

go_import_path: github.com/Prev/HotFunctions

git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

script:
  - cd worker_front && env GO111MODULE=on go build
  - cd ../load_balancer && env GO111MODULE=on go build
  - cd ./scheduler && go test
  - cd ../../simulator && go build
